[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/sick"
  to = "/sick/index.html"
  status = 200

[[redirects]]
  from = "/recall"
  to = "/recall/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/docs"
  to = "/docs/index.html"
  status = 200

[[redirects]]
  from = "/search"
  to = "/search/index.html"
  status = 200

[[redirects]]
  from = "/vacation"
  to = "/vacation/index.html"
  status = 200

[[redirects]]
  from = "/apparatus"
  to = "/apparatus/index.html"
  status = 200

[[redirects]]
  from = "/scba"
  to = "/scba/index.html"
  status = 200

[[redirects]]
  from = "/personnel"
  to = "/personnel/index.html"
  status = 200

[[redirects]]
  from = "/chat"
  to = "/search/index.html"
  status = 200

[functions."weekly-report"]
  schedule = "0 10 * * 0"

[functions."duty-cron"]
  schedule = "30 11 * * *"
